services:
  tsa-db:
    image: postgres:7-alpine
    container_name: tsa-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER} -d ${DB_NAME}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  tsa-web:
    build: .
    container_name: tsa-web
    command: gunicorn tsa_app.wsgi:application --bind 0.0.0.0:8000 --workers 4
    environment:
      MODE: prod
      DEBUG_ENABLED: 'False'
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: tsa-db
      DB_PORT: 5432
      ALLOWED_HOSTS: localhost,127.0.0.1,tsa-web
    volumes:
      - ./src/staticfiles:/app/src/staticfiles
      - ./src/media:/app/src/media
    ports:
      - '8000:8000'
    depends_on:
      tsa-db:
        condition: service_healthy

volumes:
  postgres_data:
